package report

import "time"

// ConnectionReport represents the final, immutable report generated by the Aggregator.
// No provider may mutate this struct directly.
type ConnectionReport struct {
	// Network & Identity
	IP             string    `json:"ip"`
	Hostname       string    `json:"hostname"`
	ReverseDNS     string    `json:"reverse_dns"`
	ConnectionType string    `json:"connection_type"` // e.g. "broadband", "cellular", "corporate"
	IPv4           bool      `json:"ipv4"`
	IPv6           bool      `json:"ipv6"`

	// Geo Location
	Country      string  `json:"country"`
	CountryCode  string  `json:"country_code"`
	CountryFlag  string  `json:"country_flag"`
	Region       string  `json:"region"`
	City         string  `json:"city"`
	Latitude     float64 `json:"latitude"`
	Longitude    float64 `json:"longitude"`
	Timezone     string  `json:"timezone"`

	// ISP & Network Ownership
	ISP          string `json:"isp"`
	Organization string `json:"organization"`
	ASN          int    `json:"asn"` // e.g. 15169

	// Client details
	Browser        string `json:"browser"`
	BrowserVersion string `json:"browser_version"`
	OperatingSystem string `json:"operating_system"`
	Platform       string `json:"platform"`
	Language       string `json:"language"`
	UserAgent      string `json:"user_agent"`

	// Connection Security
	HTTPS          bool   `json:"https"`
	HTTPVersion    string `json:"http_version"`
	TLSVersion     string `json:"tls_version"`
	CipherSuite    string `json:"cipher_suite"`
	ALPN           string `json:"alpn"`
	HSTS           bool   `json:"hsts"`
	OCSPStapling   bool   `json:"ocsp_stapling"`
	CertIssuer     string `json:"cert_issuer"`
	CertExpiration string `json:"cert_expiration"`
	PFS            bool   `json:"pfs"`
	SecureContext  bool   `json:"secure_context"`
	TLSDiagnostics TLSDiagnostics `json:"tls_diagnostics"`

	// Leaks & Advanced Detection
	WebRTC     bool   `json:"webrtc"`
	WebRTCLeak string `json:"webrtc_leak"` // "Safe", "Leak", "Unknown"
	DNSLeak    string `json:"dns_leak"`    // "Safe", "Leak", "Unknown"

	// Fraud & Risk Flags
	RiskScore         int                    `json:"risk_score"` // 0-100 aggregated risk
	FraudCheckEnabled bool                   `json:"fraud_check_enabled"`
	FraudProviders    []FraudProviderInsight `json:"fraud_providers"`
	Hosting           bool                   `json:"hosting"`
	VPN          bool   `json:"vpn"`
	Proxy        bool   `json:"proxy"`
	Tor          bool   `json:"tor"`
	Anonymous    bool   `json:"anonymous"`
	Mobile       bool   `json:"mobile"`
	Residential  bool   `json:"residential"`
	Datacenter   bool   `json:"datacenter"`
	ASNType      string `json:"asn_type"`
	CGNAT        bool   `json:"cgnat"`
	CarrierClass string `json:"carrier_class"`

	// External Services Availability Check
	Services map[string]bool `json:"services"` // e.g., {"netflix": false, "bbc": true}

	// Output Meta
	Summary        string         `json:"summary"`
	Score          int            `json:"score"` // 0-100 overall health score
	ScoreBreakdown ScoreBreakdown `json:"score_breakdown"`
	Status         string         `json:"status"` // "Excellent", "Good", "Warning", "Poor"
	Timestamp      time.Time      `json:"timestamp"`
}

// Request represents the incoming detection parameters extracted from the HTTP request.
type Request struct {
	IP               string
	UserAgent        string
	Headers          map[string]string
	HTTPVersion      string
	TLSVersion       string
	DirectTLSVersion string
	DirectTLSCipher  string
	DirectTLSALPN    string
}
